---
- name: create DNS record
  become: false
  route53:
    state: present
    zone: "{{ ec2_name_prefix }}.internal"
    private_zone: yes
    record: "{{ record }}"
    type: "{{ type }}"
    overwrite: true
    value: "{{ value }}"
  delegate_to: localhost    