---
- name: Configure sshd and sudoers
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    validate: "{{ item.validate | default(omit) }}"
    backup: false
  with_items: "{{ common_node_config_options }}"
  notify: restart ssh
  tags:
    - ssh
    - sudo
    - common

- name: allow new ssh hosts
  template:
    src: 90-lab.conf.j2
    dest: /etc/ssh/ssh_config.d/90-lab.conf
    owner: root
    group: root
    mode: 0644

- hostname:
    name: "{{short_name}}"

- name: Update systemd
  yum:
    name: systemd*
    state: latest
    update_cache: true

- meta: flush_handlers
  tags:
    - common
