---
- name: Advanced-Tower workshop_type
  hosts: control_nodes
  become: true
  gather_facts: false

  tasks:

  - name: create SSH key for user {{ username }}
    user:
      name: "{{ username }}"
      generate_ssh_key: true

  - name: slurp the newly created SSH key for later usage
    slurp:
      src: /home/{{ username }}/.ssh/id_rsa.pub
    register: git_authorized_key

  - name: install some additional convenience software on the control node
    package:
      name:
      - tree
      - git
      state: latest

  - name: make sure git-shell is in /etc/shells
    lineinfile:
      dest: /etc/shells
      line: /usr/bin/git-shell

  - name: git user exists and uses git-shell
    user:
      name: "{{ git_user }}"
      comment: "Git server user"
      shell: /usr/bin/git-shell

  - name: add the newly created SSH key to authorized keys
    authorized_key:
      user: "{{ git_user }}"
      state: present
      key: "{{ git_authorized_key['content'] | b64decode }}"

  # If the directory exists, we don't want to blow away its
  # contents, because it's probably got valid repo data in it!

  - name: Check Git project directory for existence
    stat:
      path: /home/{{ git_user }}/{{ git_project }}.git
    register: project_dir

  # If the directory exists, we don't want to blow away its
  # contents, because it's probably got valid repo data in it!

  - name: Create empty {{ git_project }}.git bare repository if missing
    command: git init --bare /home/{{ git_user }}/{{ git_project }}.git
    when: not (project_dir.stat.isdir is defined and project_dir.stat.isdir)

  - name: Ensure {{ git_project }}.git owned by git
    file:
      path: /home/{{ git_user }}/{{ git_project }}.git
      owner: "{{ git_user }}"
      group: "{{ git_user }}"
      recurse: yes
      mode: ug+rwX
      state: directory

  - name: add user {{ username }} to {{ git_user }} group
    user:
      name: "{{ username }}"
      groups: "{{ git_user }}"  # group has been created with the user of same name
      append: true
